;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
	evil-insert
	))

(setq mc/cmds-to-run-once
      '(
	evil-backward-char
	evil-next-line
	evil-normal-state
	evil-previous-line
	evil-repeat-find-char
	evil-search-next
	sp--self-insert-command
	))
